const path=require("path");
module.exports={
    entry:"./src/entry.js",
    output:{
        path:path.resolve(__dirname,"dist"),
        filename:"js/index.js"
    },
    module:{
        rules:[
            {
                test:/\.js$/,
                use:[
                    {loader:'babel-loader'}
                ],
                exclude:/node_modules/
            }
        ]
    }
}